### ISSUE TITLE
ReferenceError: weakly-referenced object no longer exists

### ISSUE THREAD

**Issue by lps2017H** [gems-uff/noworkflow#128]
There was a error to generate the dataflow：

[2020-08-19 17:45:49,438] ERROR in app: Exception on /trials/3/flow.pdf [GET]
Traceback (most recent call last):
  File "/Users/mrlockelwh/PycharmProjects/noworkflow/nwf/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrlockelwh/PycharmProjects/noworkflow/nwf/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrlockelwh/PycharmProjects/noworkflow/nwf/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrlockelwh/PycharmProjects/noworkflow/nwf/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/mrlockelwh/PycharmProjects/noworkflow/nwf/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrlockelwh/PycharmProjects/noworkflow/nwf/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mrlockelwh/PycharmProjects/noworkflow/noworkflow/capture/noworkflow/now/vis/views.py", line 89, in dataflow
    display = DotDisplay(trial.dot.export_text(), format="pdf")
  File "/Users/mrlockelwh/PycharmProjects/noworkflow/noworkflow/capture/noworkflow/now/models/dataflow_model.py", line 53, in export_text
    search = SearchEvaluationVisitor(clusterizer, self.activation.id)
ReferenceError: weakly-referenced object no longer exists
127.0.0.1 - - [19/Aug/2020 17:45:49] "GET /trials/3/flow.pdf HTTP/1.1" 500 -

**Comment by JoaoFelipe** [comment]
Are you using noWorkflow 1 (master branch/Pypi) or 2 (2.0-alpha branch)?

Would you be able to send me the ".noWorkflow" directory? You may send it to my email, if you do not want to share it publically: joaofelipenp@gmail.com

**Comment by lps2017H** [comment]
> Are you using noWorkflow 1 (master branch/Pypi) or 2 (2.0-alpha branch)?
> 
> Would you be able to send me the ".noWorkflow" directory? You may send it to my email, if you do not want to share it publically: [joaofelipenp@gmail.com](mailto:joaofelipenp@gmail.com)

I have send the ".noWorkflow" directory to your email, thank you! 
I am using the noworkflow 2(2.0-alpha branch)
