### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'content_engine'

### ISSUE THREAD

**Issue by manikandan-8kmiles** [gems-uff/noworkflow#129]
now export -i
Traceback (most recent call last):
  File "E:\python\Scripts\now-script.py", line 11, in <module>
    load_entry_point('noworkflow', 'console_scripts', 'now')()
  File "e:\noworkflow\capture\noworkflow\now\cmd\__init__.py", line 68, in main
    args.func(args)
  File "e:\noworkflow\capture\noworkflow\now\cmd\command.py", line 78, in _execute
    self.execute_export(args)
  File "e:\noworkflow\capture\noworkflow\now\cmd\cmd_export.py", line 57, in execute_export
    return Show().execute_export(namespace)
  File "e:\noworkflow\capture\noworkflow\now\cmd\cmd_show.py", line 109, in execute_export
    persistence_config.content_engine = args.content_engine
AttributeError: 'Namespace' object has no attribute 'content_engine'

**Comment by JoaoFelipe** [comment]
Fixed a couple months ago
