### ISSUE TITLE
Prov_execution error (KeyError)

### ISSUE THREAD

**Issue by YuzeLou** [gems-uff/noworkflow#130]
```now run -e Tracer test.py``` gets me a lot of errors similar to the following one on Linux while it works fine on Mac. Can you give some hints on how to fix this? Thanks.

```
Traceback (most recent call last):
  File "env2/lib/python2.7/site-packages/noworkflow/now/collection/prov_execution/profiler.py", line 339, in tracer
    self.event_map[event](frame, event, arg)
  File "env2/lib/python2.7/site-packages/noworkflow/now/collection/prov_execution/slicing.py", line 633, in trace_line
    self.slice_line(*activation.slice_stack.pop())
  File "env2/lib/python2.7/site-packages/noworkflow/now/collection/prov_execution/slicing.py", line 383, in slice_line
    self.slice_loop(activation, lineno, f_locals, filename)
  File "env2/lib/python2.7/site-packages/noworkflow/now/collection/prov_execution/slicing.py", line 321, in slice_loop
    loop_def = self.loops[filename].get(lineno)
KeyError: 'env2/lib/python2.7/site-packages/pandas/core/indexes/base.py'
```

**Comment by JoaoFelipe** [comment]
Hi @YuzeLou,

I finally was able to look into this issue. Unfortunately, I could not identify the source of this error ('env2/lib/python2.7/site-packages/pandas/core/indexes/base.py' should not appear there) and it occurs in a part of noWorkflow that has been completely removed for noWorkflow 2 - which is the version I'm currently supporting.

Can you check if the error occurs in the branch 2.0-alpha?

The database model has changed. So you may need to remove your current database (.noworkflow directory) to use noWorkflow 2

**Comment by JoaoFelipe** [comment]
Closing the issue since it is related to noWorklow 1.0
