### ISSUE TITLE
Erro ao executar now run

### ISSUE THREAD

**Issue by anaeletrica** [gems-uff/noworkflow#154]
Ao executar o script https://github.com/gems-uff/pypofacets/blob/master/modular_pypofacets.py) pela linha de comando:

now run modular_pypofacets.py BOX input_data_file_002.dat

Retorna o seguinte erro:
[now] TypeError("unsupported operand type(s) for +=: 'int' and 'NoneType'")
the execution finished with an uncaught exception. Traceback (most recent call last):
  File "C:\Users\rita\Documents\bla\myenv\lib\site-packages\noworkflow-2.0.0-py3.7.egg\noworkflow\now\collection\prov_execution\execution.py", line 64, in collect_provenance
    exec(compiled, metascript.namespace)  # pylint: disable=exec-used
  File "C:\Users\rita\Documents\bla\PyPOFacets\modular_pypofacets.py", line 212, in <module>
    calculate_spherical_coordinate_system_radial_unit_vector(i2s, D0, output_dir)
  File "C:\Users\rita\Documents\bla\myenv\lib\site-packages\noworkflow-2.0.0-py3.7.egg\noworkflow\now\collection\prov_execution\collector.py", line 1207, in _call
    result = future.func(*args, **kwargs)
  File "C:\Users\rita\Documents\bla\myenv\lib\site-packages\noworkflow-2.0.0-py3.7.egg\noworkflow\now\collection\prov_execution\collector.py", line 1371, in new_function_def
    activation, function_def, args, kwargs, default_values, defaults, *args, **kwargs
  File "C:\Users\rita\Documents\bla\PyPOFacets\modular_pypofacets.py", line 165, in calculate_spherical_coordinate_system_radial_unit_vector
  File "C:\Users\rita\Documents\bla\myenv\lib\site-packages\noworkflow-2.0.0-py3.7.egg\noworkflow\now\collection\prov_execution\collector.py", line 1122, in assign
    return self.assign_multiple(activation, assign, target_info, depa, ldepa, back + 1)
  File "C:\Users\rita\Documents\bla\myenv\lib\site-packages\noworkflow-2.0.0-py3.7.egg\noworkflow\now\collection\prov_execution\collector.py", line 1066, in assign_multiple
    activation, assign, target_info, custom_dependency, back + 1
  File "C:\Users\rita\Documents\bla\myenv\lib\site-packages\noworkflow-2.0.0-py3.7.egg\noworkflow\now\collection\prov_execution\collector.py", line 1083, in assign_multiple_apply
    delta += self.assign(activation, assign.sub(val, adepa), subcomp, back + 1)
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

**Comment by Felipe-CdS** [comment]
Bug não replicável, consegue dar mais informações como a sua pasta `.noworkflow`?
Algumas notas sobre o problema a partir do log que enviou:
- Seus logs mostram que usou python 3.7. Por favor, tente o mesmo processo com python 3.8 e a versão mais nova na master do noWorkflow.
- [modular_pypofacets.py](https://github.com/gems-uff/pypofacets/blob/master/modular_pypofacets.py) não existe mais no seu repositório. Eu testei com [modular_expert_pypofacets.py](https://github.com/gems-uff/pypofacets/blob/master/modular_expert_pypofacets.py) e [modular_llm_pypofacets.py](https://github.com/gems-uff/pypofacets/blob/master/modular_llm_pypofacets.py) e ambos funcionaram corretamente.

<img width="1312" height="741" alt="Image" src="https://github.com/user-attachments/assets/dd9eaefc-a4a1-4c51-a72b-27987ba895ca" />

<img width="1311" height="739" alt="Image" src="https://github.com/user-attachments/assets/eff513a3-11c6-4a3b-abc6-ca3c38c9579b" />

**Comment by Felipe-CdS** [comment]
Commit [2629397](https://github.com/gems-uff/noworkflow/commit/26293971b829b3ced8190231d6da20719e80ceef) é um fix para esse erro. Ticket fechado.
