### ISSUE TITLE
Error while using Tracer

### ISSUE THREAD

**Issue by braganholo** [gems-uff/noworkflow#80]
I tried to execute noWorkflow with Tracer, and got an error. It runs with no error if I don't use the Tracer (now run simulate_data_collection.py)

Ramster:simulate_data_collection vanessa$ now run -e Tracer simulate_data_collection.py
Traceback (most recent call last):
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 201, in tracer
    super(Profiler, self).tracer(frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/base.py", line 53, in tracer
    self.event_map[event](frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 149, in trace_call
    self.argument_captor.capture(frame, activation)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/argument_captors.py", line 212, in capture
    act_arg = order[j]
IndexError: list index out of range
Traceback (most recent call last):
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 201, in tracer
    super(Profiler, self).tracer(frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/base.py", line 53, in tracer
    self.event_map[event](frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 149, in trace_call
    self.argument_captor.capture(frame, activation)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/argument_captors.py", line 212, in capture
    act_arg = order[j]
IndexError: list index out of range
Traceback (most recent call last):
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 201, in tracer
    super(Profiler, self).tracer(frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/base.py", line 53, in tracer
    self.event_map[event](frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/slicing.py", line 382, in trace_line
Traceback (most recent call last):
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 201, in tracer
    super(Profiler, self).tracer(frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/base.py", line 53, in tracer
    self.event_map[event](frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/slicing.py", line 382, in trace_line
Traceback (most recent call last):
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 201, in tracer
    super(Profiler, self).tracer(frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/base.py", line 53, in tracer
    self.event_map[event](frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/slicing.py", line 382, in trace_line
Traceback (most recent call last):
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 201, in tracer
    super(Profiler, self).tracer(frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/base.py", line 53, in tracer
    self.event_map[event](frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/slicing.py", line 382, in trace_line
Traceback (most recent call last):
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 201, in tracer
    super(Profiler, self).tracer(frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/base.py", line 53, in tracer
    self.event_map[event](frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 145, in trace_call
    self.activation_stack[-1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 201, in tracer
    super(Profiler, self).tracer(frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/base.py", line 53, in tracer
    self.event_map[event](frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/slicing.py", line 382, in trace_line
Traceback (most recent call last):
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 201, in tracer
    super(Profiler, self).tracer(frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/base.py", line 53, in tracer
    self.event_map[event](frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 145, in trace_call
    self.activation_stack[-1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 201, in tracer
    super(Profiler, self).tracer(frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/base.py", line 53, in tracer
    self.event_map[event](frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 182, in trace_return
    self.close_activation(frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/slicing.py", line 288, in close_activation
Traceback (most recent call last):
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 201, in tracer
    super(Profiler, self).tracer(frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/base.py", line 53, in tracer
    self.event_map[event](frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/slicing.py", line 382, in trace_line
Traceback (most recent call last):
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 201, in tracer
    super(Profiler, self).tracer(frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/base.py", line 53, in tracer
    self.event_map[event](frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 145, in trace_call
    self.activation_stack[-1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 201, in tracer
    super(Profiler, self).tracer(frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/base.py", line 53, in tracer
    self.event_map[event](frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/slicing.py", line 382, in trace_line
Traceback (most recent call last):
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 201, in tracer
    super(Profiler, self).tracer(frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/base.py", line 53, in tracer
    self.event_map[event](frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 182, in trace_return
    self.close_activation(frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/slicing.py", line 288, in close_activation
Traceback (most recent call last):
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 201, in tracer
    super(Profiler, self).tracer(frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/base.py", line 53, in tracer
    self.event_map[event](frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 182, in trace_return
    self.close_activation(frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/slicing.py", line 288, in close_activation
Traceback (most recent call last):
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 201, in tracer
    super(Profiler, self).tracer(frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/base.py", line 53, in tracer
    self.event_map[event](frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 182, in trace_return
    self.close_activation(frame, event, arg)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/slicing.py", line 288, in close_activation
list index out of range
[now] the execution finished with an uncaught exception. Traceback (most recent call last):
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/__init__.py", line 54, in collect_provenance
    exec(metascript.compiled, metascript.namespace)
  File "/Users/vanessa/workspace/yw-prototypes/src/main/resources/examples/simulate_data_collection/simulate_data_collection.py", line 273, in <module>
    simulate_data_collection(cassette_id, sample_score_cutoff)
  File "/Users/vanessa/workspace/yw-prototypes/src/main/resources/examples/simulate_data_collection/simulate_data_collection.py", line 34, in simulate_data_collection
    with run_logger(log_file_name="run/run_log.txt") as run_log:
  File "/Users/vanessa/workspace/yw-prototypes/src/main/resources/examples/simulate_data_collection/simulate_data_collection.py", line 227, in __init__
    self.log_file = open(log_file_name, 'wt') if log_file_name is not None else None
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/base.py", line 101, in open
    self.add_file_access(file_access)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 88, in add_file_access
    activation = self._current_activation(ignore_open=True)
  File "/Users/vanessa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/noworkflow/now/prov_execution/profiler.py", line 78, in _current_activation
    if astack[-1] is not None:
IndexError: list index out of range

**Comment by JoaoFelipe** [comment]
It seems to be a bug related to a for loop inside a with.
I could reproduce it with the following code:
```python
class ContextManager:

    def __enter__(self):
        return 2

    def __exit__(self, *args, **kwargs):
        pass

def func():
    context = ContextManager()

    with context as value:
        for i in range(value):
            print(i)

func()
```

It occurs because we try to get the calls by lineno and lasti on the bytecode.
WITH_CLEANUP opcode results in a call to __exit__.
By capturing line and lasti of WITH_CLEANUP, we can usually detect the calls. However, in this specific case, the loop mess up with the the lineno, and it fails to obtain the definition of with from the bytecode.
The best way to match the run-time "with" and the bytecode WITH_CLEANUP would be using only the lasti in the code object. 
Since I don't know how to identify the code object in the disassembly, and it would require some time to replace references from lines to code objects, I'll keep the current solution, but silently ignore calls with messed up linenos.
For now, it will be fine. If we improve some collection on with statements (to capture exceptions, for instance), it may be a problem. Hopefully, we will only do that after #84
